### ISSUE TITLE
Dockerimage - Questions

### ISSUE THREAD

**Issue by NeurosProjekte** [ssewell/Elegoo3DPrinterMonitor#17]
Hey There,
I tried your Dockerimage from Dockerhub and saw that there are two ports in there:
3000 for normal webpage and 5000 for a site to work with get arguments. that could be a way to copy the status from my printer into my smarthome, but i couldn't find any documentation for the arguments that could be used there. Are there any informations about that docker somewhere so that I could get used to it?

Couldn't find any other way to get in contact with you, so I had to open an issue here.

**Comment by ssewell** [comment]
Glad you're exploring the app! The Elegoo3DPrinterMonitor is designed to provide a way to monitor compatible 3D printers on your LAN and display via its own UI. I don't have any plans to implement an API that would allow for further integration with smart home tech as it's outside the scope of the project.
