### ISSUE TITLE
View Printers on a VLAN other than the app's host?

### ISSUE THREAD

**Issue by Soygen** [ssewell/Elegoo3DPrinterMonitor#18]
My main PC is on my main network and my Mars 4 Ultra is on VLAN under the same router. Is there a way to configure this so I can point it to a specific IP, as the app does not detect my printer over the VLAN?

**Comment by ssewell** [comment]
The Elegoo3DPrinterMonitor uses UDP broadcasts to query the status of any printers on your LAN and is subject to the limitations of VLAN tagging (won't be able to "see" network traffic on other isolated VLANS). 

If you have a compute resource available on the same VLAN as your Mars 4 Ultra, you could try running the [experimental web version](https://github.com/ssewell/Elegoo3DPrinterMonitorWeb) of the monitor either as a service or docker container.

**Comment by Soygen** [comment]
I do have a couple VMs on the same VLAN. Will give the web version a shot. Thanks!
